### ISSUE TITLE
3.1 version cannot be built

### ISSUE THREAD

**Issue by cvogt** [typesafehub/activator-hello-slick#25]
```
Switched to a new branch 'slick-3.1'
localhost:activator-hello-slick chris$ sbt 
[info] Loading global plugins from /Users/chris/.sbt/0.13/plugins
[info] Loading project definition from /Users/chris/code/forks/activator-hello-slick/project
[info] Updating {file:/Users/chris/code/forks/activator-hello-slick/project/}activator-hello-slick-build...
[info] Resolving net.contentobjects.jnotify#jnotify;0.94 ...
[warn]  module not found: net.contentobjects.jnotify#jnotify;0.94
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/net.contentobjects.jnotify/jnotify/0.94/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/net.contentobjects.jnotify/jnotify/0.94/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/chris/.ivy2/local/net.contentobjects.jnotify/jnotify/0.94/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/net/contentobjects/jnotify/jnotify/0.94/jnotify-0.94.pom
[warn] ==== CBT Maven Cache: tried
[warn]   file:///Users/chris/code/cbt/cache/maven/net/contentobjects/jnotify/jnotify/0.94/jnotify-0.94.pom
[info] Resolving com.typesafe#jse_2.10;1.0.0 ...
[warn]  module not found: com.typesafe#jse_2.10;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe/jse_2.10/1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe/jse_2.10/1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/chris/.ivy2/local/com.typesafe/jse_2.10/1.0.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/jse_2.10/1.0.0/jse_2.10-1.0.0.pom
[warn] ==== CBT Maven Cache: tried
[warn]   file:///Users/chris/code/cbt/cache/maven/com/typesafe/jse_2.10/1.0.0/jse_2.10-1.0.0.pom
[info] Resolving com.typesafe#npm_2.10;1.0.0 ...
[warn]  module not found: com.typesafe#npm_2.10;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe/npm_2.10/1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe/npm_2.10/1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/chris/.ivy2/local/com.typesafe/npm_2.10/1.0.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/npm_2.10/1.0.0/npm_2.10-1.0.0.pom
[warn] ==== CBT Maven Cache: tried
[warn]   file:///Users/chris/code/cbt/cache/maven/com/typesafe/npm_2.10/1.0.0/npm_2.10-1.0.0.pom
[info] Resolving com.typesafe#webdriver_2.10;1.0.0 ...
[warn]  module not found: com.typesafe#webdriver_2.10;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe/webdriver_2.10/1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe/webdriver_2.10/1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/chris/.ivy2/local/com.typesafe/webdriver_2.10/1.0.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/webdriver_2.10/1.0.0/webdriver_2.10-1.0.0.pom
[warn] ==== CBT Maven Cache: tried
[warn]   file:///Users/chris/code/cbt/cache/maven/com/typesafe/webdriver_2.10/1.0.0/webdriver_2.10-1.0.0.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/sbt-fork-run-plugin/scala_2.10/sbt_0.13/2.3.9/jars/sbt-fork-run-plugin.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#sbt-fork-run-plugin;2.3.9!sbt-fork-run-plugin.jar (826ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/sbt-fork-run-protocol_2.10/2.3.9/sbt-fork-run-protocol_2.10-2.3.9.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#sbt-fork-run-protocol_2.10;2.3.9!sbt-fork-run-protocol_2.10.jar (267ms)
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.3.9/jars/sbt-plugin.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#sbt-plugin;2.3.9!sbt-plugin.jar (1560ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/sbt-run-support_2.10/2.3.9/sbt-run-support_2.10-2.3.9.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#sbt-run-support_2.10;2.3.9!sbt-run-support_2.10.jar (139ms)
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbtrc/client-2-10/0.3.1/jars/client-2-10.jar ...
[info]  [SUCCESSFUL ] com.typesafe.sbtrc#client-2-10;0.3.1!client-2-10.jar (1160ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/build-link/2.3.9/build-link-2.3.9.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#build-link;2.3.9!build-link.jar (126ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-exceptions/2.3.9/play-exceptions-2.3.9.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-exceptions;2.3.9!play-exceptions.jar (127ms)
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/launcher-interface/0.13.8-M3/jars/launcher-interface.jar ...
[info]  [SUCCESSFUL ] org.scala-sbt#launcher-interface;0.13.8-M3!launcher-interface.jar (713ms)
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.8-M3/jars/interface.jar ...
[info]  [SUCCESSFUL ] org.scala-sbt#interface;0.13.8-M3!interface.jar (858ms)
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.8-M3/jars/io.jar ...
[info]  [SUCCESSFUL ] org.scala-sbt#io;0.13.8-M3!io.jar (863ms)
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.8-M3/jars/collections.jar ...
[info]  [SUCCESSFUL ] org.scala-sbt#collections;0.13.8-M3!collections.jar (882ms)
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.8-M3/jars/control.jar ...
[info]  [SUCCESSFUL ] org.scala-sbt#control;0.13.8-M3!control.jar (735ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/routes-compiler_2.10/2.3.9/routes-compiler_2.10-2.3.9.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#routes-compiler_2.10;2.3.9!routes-compiler_2.10.jar (171ms)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: net.contentobjects.jnotify#jnotify;0.94: not found
[warn]  :: com.typesafe#jse_2.10;1.0.0: not found
[warn]  :: com.typesafe#npm_2.10;1.0.0: not found
[warn]  :: com.typesafe#webdriver_2.10;1.0.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      net.contentobjects.jnotify:jnotify:0.94
[warn]        +- com.typesafe.play:sbt-plugin:2.3.9 (scalaVersion=2.10, sbtVersion=0.13)
[warn]        +- com.typesafe.play:sbt-fork-run-plugin:2.3.9 (scalaVersion=2.10, sbtVersion=0.13) (/Users/chris/code/forks/activator-hello-slick/project/play-fork-run.sbt#L3-4)
[warn]        +- default:activator-hello-slick-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn]      com.typesafe:jse_2.10:1.0.0
[warn]        +- com.typesafe.sbt:sbt-js-engine:1.0.1 (scalaVersion=2.10, sbtVersion=0.13)
[warn]        +- com.typesafe.play:sbt-plugin:2.3.9 (scalaVersion=2.10, sbtVersion=0.13)
[warn]        +- com.typesafe.play:sbt-fork-run-plugin:2.3.9 (scalaVersion=2.10, sbtVersion=0.13) (/Users/chris/code/forks/activator-hello-slick/project/play-fork-run.sbt#L3-4)
[warn]        +- default:activator-hello-slick-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn]      com.typesafe:npm_2.10:1.0.0
[warn]        +- com.typesafe.sbt:sbt-js-engine:1.0.1 (scalaVersion=2.10, sbtVersion=0.13)
[warn]        +- com.typesafe.play:sbt-plugin:2.3.9 (scalaVersion=2.10, sbtVersion=0.13)
[warn]        +- com.typesafe.play:sbt-fork-run-plugin:2.3.9 (scalaVersion=2.10, sbtVersion=0.13) (/Users/chris/code/forks/activator-hello-slick/project/play-fork-run.sbt#L3-4)
[warn]        +- default:activator-hello-slick-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn]      com.typesafe:webdriver_2.10:1.0.0
[warn]        +- com.typesafe.sbt:sbt-webdriver:1.0.0 (scalaVersion=2.10, sbtVersion=0.13)
[warn]        +- com.typesafe.play:sbt-plugin:2.3.9 (scalaVersion=2.10, sbtVersion=0.13)
[warn]        +- com.typesafe.play:sbt-fork-run-plugin:2.3.9 (scalaVersion=2.10, sbtVersion=0.13) (/Users/chris/code/forks/activator-hello-slick/project/play-fork-run.sbt#L3-4)
[warn]        +- default:activator-hello-slick-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: net.contentobjects.jnotify#jnotify;0.94: not found
unresolved dependency: com.typesafe#jse_2.10;1.0.0: not found
unresolved dependency: com.typesafe#npm_2.10;1.0.0: not found
unresolved dependency: com.typesafe#webdriver_2.10;1.0.0: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
    at sbt.IvySbt.withIvy(Ivy.scala:123)
    at sbt.IvySbt.withIvy(Ivy.scala:120)
    at sbt.IvySbt$Module.withModule(Ivy.scala:151)
    at sbt.IvyActions$.updateEither(IvyActions.scala:157)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: net.contentobjects.jnotify#jnotify;0.94: not found
[error] unresolved dependency: com.typesafe#jse_2.10;1.0.0: not found
[error] unresolved dependency: com.typesafe#npm_2.10;1.0.0: not found
[error] unresolved dependency: com.typesafe#webdriver_2.10;1.0.0: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by eed3si9n** [comment]
jnotify is hosted under https://repo.typesafe.com/typesafe/maven-releases/.
